# Generated by Django 5.1.4 on 2025-01-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('0', 'Nil'), ('1', 'Trainee'), ('2', 'Software Engineer'), ('3', 'Senior Software Engineer'), ('4', 'Project Manager'), ('5', 'UI/UX Engineer'), ('6', 'Senior UI/UX Engineer'), ('7', 'Software Tester')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('withdrawn', 'Withdrawn'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('archived', 'Archived')], max_length=128)),
                ('comment', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_portal_app.employee')),
            ],
        ),
    ]
