# Generated by Django 5.1.4 on 2025-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0002_alter_employee_position_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
