# Generated by Django 5.1.4 on 2025-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0003_alter_project_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('resigned', 'Resigned'), ('terminated', 'Terminated'), ('temporarily_not_exists', 'Temporarily not Exists'), ('deceased', 'Deceased'), ('active', 'Active'), ('not_active', 'Not Active')], default='active', max_length=50),
        ),
    ]
