# Generated by Django 5.1.4 on 2025-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0004_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
