# Generated by Django 5.1.4 on 2025-02-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0005_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignation',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('withdrawn', 'Withdrawn'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('archived', 'Archived')], max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigning_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_assignations', to='emp_portal_app.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='emp_portal_app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_portal_app.project')),
            ],
        ),
    ]
