# Generated by Django 5.1.4 on 2025-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0008_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
