# Generated by Django 5.1.4 on 2025-03-18 12:35

import django.db.models.deletion
import emp_portal_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0009_employee_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Shift', max_length=50, unique=True)),
                ('start_time', models.TimeField(default='03:30:00')),
                ('end_time', models.TimeField(default='12:30:00')),
                ('total_hours', models.FloatField(default=8.0)),
                ('working_days', models.JSONField(default=emp_portal_app.models.default_working_days)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_check_in', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_portal_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_portal_app.shift'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('total_worked_seconds', models.IntegerField(default=0)),
                ('attendance_status', models.CharField(choices=[('first_half_present', 'First Half Present'), ('second_half_present', 'Second Half Present'), ('full_day_present', 'Full Day Present'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_portal_app.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date')],
            },
        ),
    ]
