# Generated by Django 5.1.4 on 2025-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0010_shift_checkinout_employee_shift_attendance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_employee_date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
