# Generated by Django 5.1.4 on 2025-03-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0011_remove_attendance_unique_employee_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
