# Generated by Django 5.1.7 on 2025-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_portal_app', '0012_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='leave_id_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
